#!/bin/bash
echo "Enter the Blue Key Password: "
read x

if [ $x == "+3yy<0" ] 
then 
	echo "You look around the Medical Room. The floor is scattered with blood and papers. The smell of sterile plastic and iron makes your heart lurch. 

Instruments and pills are knocked over.
You see the note. You notice the another Research Document on the floor. There is a red key hanging on the board.

You almost step on a scalpel on the floor.

To pick up items: ./.acquire.sh
To pick up the red key: mv Red_Key Keychain 
To read the note: cat note


After you collected and observed the room you notice a door that is cracked. Muffled gasping and gurgling is heard from the entrance way.

To brave foward the room: cd Lab_Room"
else
	echo "Access Denied"
fi
