#!/bin/bash
echo "Enter the Blue Key Password: "
read x

if [ $x == "+3yy<0" ] 
then 
	echo "You look around the Medical Room. The floor is scattered with blood and papers. The smell of sterile plastic and iron makes your heart lurch. 

Instruments and pills are knocked over.
You see the note. You notice the another Research Document on the floor. There is a red key hanging on the board.
You almost step on a scalpel on the floor.


// pick up items: mv doc_2 Control_Room
// pick up the red key: mv red_key Control_Room
// read the note: cat note
// pick up the scalpel: mv scalpel Control_Room

  
  
After you collected and observed the room you notice a door that is cracked. Muffled gasping and gurgling is heard from the entrance way.

// brave the room: cd Lab_Room"
else
	echo "Access Denied"
fi
