#!/bin/bash
echo "Enter the Red Key Password:"
read x
if [ $x == "@_v#7[" ]
then 
	echo "You look around the Office Room.

There are papers and binders all over the floor. 
The desks and chairs are overturned.

You see another Research Document on a chair. To move it to the Control Room:
  ./.acquire.sh
 
There is a map on one of the desks. To see the map:
  cat map
  
You find a purple key under crumped paper. To move the key to the Control Room:
  mv Purple_key ~/ProjectOpis/Control_Room/Keychain
  
In the corner, you see a toolbox. Move toolbox to the Control Room: 
  ./.acquire.sh"
else 
	echo "Access Denied"
fi
