#!/bin/bash
echo " "
echo " The engine is sputtering, alarms and flashing red lights cloud your vision."
echo " You run to the engine frantically trying to find a way to fix it."
echo " You feel the gravity of the planet below pulling, you are very close to hitting Opis's surface."
echo " You run over to the engine looking to fix it."
echo " ---------------------------------------------------------------------------------------------------"
gameDir=$PWD
  sleep 1
    if  grep -Fxq "doc_1" inventory  &&  grep -Fxq "doc_2" inventory  &&  grep -Fxq "doc_3" inventory  && grep -Fxq "doc_5" inventory && grep -Fxq "doc_4" inventory && grep -Fxq "doc_6" inventory && grep -Fxq "tool_box" inventory
then
        echo "Pulling out your toolkit you get set to work."
        echo "Your hands work as if in second nature, as the engine seems to fix itself"
        echo "You step back and smile, the engine is fixed."
        echo "The ship starts to warp and auto poilot takes over."
        echo "You are going home."
        echo "You stand back content and pull out the completed research."
	echo "With the cure found and the ship fixed ypu can save your people."
        echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"        
        echo " "        
        echo "Game over."
    elif  grep -Fxq "tool_box" inventory
 then
        echo "Pulling out your toolkit you get set to work."
        echo "Your hands work as if in second nature, as the engine seems to fix itself"
        echo "You step back and smile, the engine is fixed."
        echo "The ship starts to warp and auto poilot takes over."
        echo "You are going home."
	echo "A sinking feeling pools at the bottom of your stomach."
	echo "The research is incomplete."
	echo "You are alive but your people are doomed."
        echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"        
        echo " "
        echo "Game over."
        rm -rf Project
     else
        echo "Reaching the engine you look around"
        echo "No tools litter the floor just broken pieces of machinery."
        echo "The planet is getting closer and closer."
        echo "Closing your eyes you brace for impact knowing that your planet will not be saved."
        echo "The sabatours won."
        echo "The ship crashes and you do not make it."
        echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" 
        echo " "
        echo "Game over."
cd /home/gameDir/ProjectOpis
        rm -rf home/gameDir/ProjectOpis
    fi
