#!/bin/bash
user=$PWD
if grep -Fxq "Scalpel" inventory; then
    echo
    echo "They lung towards you."
    echo "You recall the scalpel you picked up in the med room."
    echo "In one defensive motion, you kill the crewmate."
    echo "Their blood splattered among your face you stand in shock."
    echo "They were once your friend."
    echo "Pulling yourself out of the stupor you notice part of the research behind them."
    echo
    echo "You should pick up the Document 3"
    echo "To acquire the Document 3: type ./.acquire.sh doc_3"
    echo "To delete your crewmate: type 'rm Crewmate'"
    echo
else
    sleep 1
    echo
    echo "Get out of there now! You have no way to defend yourself!"
    echo "It's to late, your crewmate is advancing on you."
    echo "You put your fists up in defense."
    echo "But it is nothing compared to their strength."
    echo "You were overpowered."
    echo 
    echo "Game Over. Restart the game "
    exit
    exit
  rm -fr ProjectOpis/
fi
