#!/bin/bash
echo
echo "Pushing open the door you are met with a horrific sight. The bloody, expiremented body of you missing crewmate is hunched over the desk.
They quickly turn their head as you walk in, their mangled face shaking you to the core. You had no idea the side affects could be so... So utterly dreadful.
You notice a piece of the research in their hand.  
But to reach there you have to go through what used to be your friend.
Do you engage or leave them in peace?

To engage: ./Crewmate
To go back to Medical Room: cd .."
echo
